// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:fe958049-742a-4109-a054-1fc3c1e12961",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_ejXqOp6Rc",
    "aws_user_pools_web_client_id": "4senr5vpdbmqkm6db9edrmsou",
    "aws_content_delivery_bucket": "mpgclient23-20181207152029--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://dkudnc0fwio9i.cloudfront.net"
};


export default awsmobile;
